const DATA = [
  {
    Word: "Care",
    Translation: "Турбота, догляд",
    Category: "Verb",
    Progress: 90,
    Edit: "edit",
  },
  {
    Word: "Until",
    Translation: "Протягом, під час",
    Category: "Preposition",
    Progress: 90,
    Edit: "edit",
  },
  {
    Word: "Happy",
    Translation: "Щасливий",
    Category: "Adjective",
    Progress: 70,
    Edit: "edit",
  },
  {
    Word: "Travel",
    Translation: "Подорожувати",
    Category: "Verb",
    Progress: 85,
    Edit: "edit",
  },
  {
    Word: "Book",
    Translation: "Книга",
    Category: "Noun",
    Progress: 95,
    Edit: "edit",
  },
  {
    Word: "Dog",
    Translation: "Собака",
    Category: "Noun",
    Progress: 80,
    Edit: "edit",
  },
  {
    Word: "Run",
    Translation: "Бігти",
    Category: "Verb",
    Progress: 75,
    Edit: "edit",
  },
  {
    Word: "Friend",
    Translation: "Друг",
    Category: "Noun",
    Progress: 90,
    Edit: "edit",
  },
  {
    Word: "Quickly",
    Translation: "Швидко",
    Category: "Adverb",
    Progress: 85,
    Edit: "edit",
  },
  {
    Word: "Idea",
    Translation: "Ідея",
    Category: "Noun",
    Progress: 88,
    Edit: "edit",
  },
  {
    Word: "Think",
    Translation: "Думати",
    Category: "Verb",
    Progress: 82,
    Edit: "edit",
  },
  {
    Word: "Blue",
    Translation: "Синій",
    Category: "Adjective",
    Progress: 77,
    Edit: "edit",
  },
  {
    Word: "Under",
    Translation: "Під",
    Category: "Preposition",
    Progress: 90,
    Edit: "edit",
  },
  {
    Word: "Eat",
    Translation: "Їсти",
    Category: "Verb",
    Progress: 80,
    Edit: "edit",
  },
  {
    Word: "Sleep",
    Translation: "Спати",
    Category: "Verb",
    Progress: 85,
    Edit: "edit",
  },
  {
    Word: "Beautiful",
    Translation: "Красивий",
    Category: "Adjective",
    Progress: 78,
    Edit: "edit",
  },
  {
    Word: "Above",
    Translation: "Над",
    Category: "Preposition",
    Progress: 82,
    Edit: "edit",
  },
  {
    Word: "Table",
    Translation: "Стіл",
    Category: "Noun",
    Progress: 92,
    Edit: "edit",
  },
  {
    Word: "Write",
    Translation: "Писати",
    Category: "Verb",
    Progress: 87,
    Edit: "edit",
  },
  {
    Word: "Read",
    Translation: "Читати",
    Category: "Verb",
    Progress: 85,
    Edit: "edit",
  },
  {
    Word: "Slowly",
    Translation: "Повільно",
    Category: "Adverb",
    Progress: 80,
    Edit: "edit",
  },
  {
    Word: "Red",
    Translation: "Червоний",
    Category: "Adjective",
    Progress: 75,
    Edit: "edit",
  },
  {
    Word: "Window",
    Translation: "Вікно",
    Category: "Noun",
    Progress: 88,
    Edit: "edit",
  },
  {
    Word: "During",
    Translation: "Протягом",
    Category: "Preposition",
    Progress: 90,
    Edit: "edit",
  },
  {
    Word: "Love",
    Translation: "Любити",
    Category: "Verb",
    Progress: 85,
    Edit: "edit",
  },
  {
    Word: "Car",
    Translation: "Автомобіль",
    Category: "Noun",
    Progress: 89,
    Edit: "edit",
  },
  {
    Word: "Black",
    Translation: "Чорний",
    Category: "Adjective",
    Progress: 77,
    Edit: "edit",
  },
  {
    Word: "Help",
    Translation: "Допомагати",
    Category: "Verb",
    Progress: 83,
    Edit: "edit",
  },
  {
    Word: "Before",
    Translation: "Перед",
    Category: "Preposition",
    Progress: 85,
    Edit: "edit",
  },
  {
    Word: "Quick",
    Translation: "Швидкий",
    Category: "Adjective",
    Progress: 82,
    Edit: "edit",
  },
  {
    Word: "Eat",
    Translation: "Їсти",
    Category: "Verb",
    Progress: 90,
    Edit: "edit",
  },
  {
    Word: "Mountain",
    Translation: "Гора",
    Category: "Noun",
    Progress: 88,
    Edit: "edit",
  },
  {
    Word: "Fast",
    Translation: "Швидко",
    Category: "Adverb",
    Progress: 85,
    Edit: "edit",
  },
  {
    Word: "Kind",
    Translation: "Добрий",
    Category: "Adjective",
    Progress: 80,
    Edit: "edit",
  },
  {
    Word: "Below",
    Translation: "Нижче",
    Category: "Preposition",
    Progress: 82,
    Edit: "edit",
  },
  {
    Word: "Chair",
    Translation: "Стілець",
    Category: "Noun",
    Progress: 90,
    Edit: "edit",
  },
  {
    Word: "Work",
    Translation: "Працювати",
    Category: "Verb",
    Progress: 87,
    Edit: "edit",
  },
  {
    Word: "See",
    Translation: "Бачити",
    Category: "Verb",
    Progress: 85,
    Edit: "edit",
  },
  {
    Word: "Never",
    Translation: "Ніколи",
    Category: "Adverb",
    Progress: 80,
    Edit: "edit",
  },
  {
    Word: "Yellow",
    Translation: "Жовтий",
    Category: "Adjective",
    Progress: 75,
    Edit: "edit",
  },
  {
    Word: "Phone",
    Translation: "Телефон",
    Category: "Noun",
    Progress: 88,
    Edit: "edit",
  },
  {
    Word: "Between",
    Translation: "Між",
    Category: "Preposition",
    Progress: 90,
    Edit: "edit",
  },
  {
    Word: "Run",
    Translation: "Бігти",
    Category: "Verb",
    Progress: 85,
    Edit: "edit",
  },
  {
    Word: "Child",
    Translation: "Дитина",
    Category: "Noun",
    Progress: 89,
    Edit: "edit",
  },
  {
    Word: "Green",
    Translation: "Зелений",
    Category: "Adjective",
    Progress: 77,
    Edit: "edit",
  },
  {
    Word: "Teach",
    Translation: "Вчити",
    Category: "Verb",
    Progress: 83,
    Edit: "edit",
  },
  {
    Word: "After",
    Translation: "Після",
    Category: "Preposition",
    Progress: 85,
    Edit: "edit",
  },
  {
    Word: "Bright",
    Translation: "Яскравий",
    Category: "Adjective",
    Progress: 82,
    Edit: "edit",
  },
  {
    Word: "Food",
    Translation: "Їжа",
    Category: "Noun",
    Progress: 90,
    Edit: "edit",
  },
  {
    Word: "Jump",
    Translation: "Стрибати",
    Category: "Verb",
    Progress: 88,
    Edit: "edit",
  },
  {
    Word: "Always",
    Translation: "Завжди",
    Category: "Adverb",
    Progress: 85,
    Edit: "edit",
  },
  {
    Word: "Soft",
    Translation: "М'який",
    Category: "Adjective",
    Progress: 80,
    Edit: "edit",
  },
  {
    Word: "With",
    Translation: "З",
    Category: "Preposition",
    Progress: 82,
    Edit: "edit",
  },
];

export default DATA;
