const DATA = [
  {
    Word: "Care",
    Translation: "Турбота, догляд",
    Category: "Verb",
    Progress: 90,
    Edit: "edit",
  },
  {
    Word: "Until",
    Translation: "Протягом, під час",
    Category: "Preposition",
    Progress: 90,
    Edit: "edit",
  },
  {
    Word: "Happy",
    Translation: "Щасливий",
    Category: "Adjective",
    Progress: 70,
    Edit: "edit",
  },
  {
    Word: "Travel",
    Translation: "Подорожувати",
    Category: "Verb",
    Progress: 85,
    Edit: "edit",
  },
  {
    Word: "Book",
    Translation: "Книга",
    Category: "Noun",
    Progress: 95,
    Edit: "edit",
  },
  // Additional examples
  {
    Word: "Dog",
    Translation: "Собака",
    Category: "Noun",
    Progress: 80,
    Edit: "edit",
  },
  {
    Word: "Run",
    Translation: "Бігти",
    Category: "Verb",
    Progress: 75,
    Edit: "edit",
  },
  {
    Word: "Friend",
    Translation: "Друг",
    Category: "Noun",
    Progress: 90,
    Edit: "edit",
  },
  {
    Word: "Quickly",
    Translation: "Швидко",
    Category: "Adverb",
    Progress: 85,
    Edit: "edit",
  },
  {
    Word: "Idea",
    Translation: "Ідея",
    Category: "Noun",
    Progress: 88,
    Edit: "edit",
  },
  {
    Word: "Think",
    Translation: "Думати",
    Category: "Verb",
    Progress: 82,
    Edit: "edit",
  },
  {
    Word: "Blue",
    Translation: "Синій",
    Category: "Adjective",
    Progress: 77,
    Edit: "edit",
  },
  {
    Word: "Under",
    Translation: "Під",
    Category: "Preposition",
    Progress: 90,
    Edit: "edit",
  },
];

export default DATA;
